---
title: "Homework 2"
author: "Felix and Renee"
date: "2022-11-09"
output: html_document # need to make this pdf/doc
editor_options: 
  chunk_output_type: console
params:
    numKeywords: 10
    printcode: false
    colors: !r c("slateblue4","skyblue4","paleturquoise4","slateblue3","skyblue3","paleturquoise3", "powderblue","slateblue1","skyblue1","paleturquoise1")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$printcode)
library(psych)
library(knitr)
library(stringr)
library(wordcloud)
# install.packages("wordcloud")
```

```{r readData}
allWorks <- readRDS("allWorks.rds")
```

### Statistics, plots and figures

a. In total, there are `r nrow(allWorks)` works in the dataset.

b. 

```{r distribution plot type of works}

# preparing the barplot

types <- table(allWorks$TY)
type_names <- c("Journal paper", "Conference paper", "Chapter")
par(mar=c(2,8,2,1)) # how to i make the figure smaller without cutting of the labels?

# making the barplot

barplot(sort(types, decreasing = TRUE),
        main="Type of works",
        horiz= TRUE,
        xlim=c(0,45),
        las = 1,
        names.arg = type_names,
        col=params$colors[c(1,4,8)])

```

c.

```{r descriptive statistics}

# preparing the (A B C) columns

allWorks$length_titles <- nchar(allWorks$TI) # is it ok that it includes spaces?

sep <- ";"
count <- str_count(allWorks$AU, sep)
allWorks$number_authors <- count+1

allWorks$publ_year <- as.integer(allWorks$PY)

# making a list

tmpList <- list(length_titles=allWorks$length_titles, number_authors=allWorks$number_authors, publ_year=allWorks$publ_year)

# making the table 

statstable <- rbind(describe(allWorks[,c("length_titles","number_authors","publ_year")]))[,c("n","mean","sd","min","max","skew","kurtosis")]
kable(statstable, caption = "Descriptive statistics")
```

```{r histograms, fig.cap=paste("Histogram of",names(tmpList)), fig.height=4, fig.width=5}

for(iVar in names(tmpList)){
  hist(tmpList[[iVar]], xlab=iVar, main="", xaxs="i", yaxs="i", col=params$colors[1:10])
  cat("\n\n")
}

```

d.

```{r barplot, fig.cap="Most frequent keywords (first 10)"}

keywords <- table(tolower(unlist(strsplit(allWorks[,4], split = ";"))))
keywords.2 <- sort(keywords, decreasing = TRUE)

par(mar=c(3,20,4,1))
barplot(keywords.2[1:params$numKeywords],
        main="",
        horiz= TRUE,
        las = 1,
        col=params$colors[1:params$numKeywords]
        )

```

e.

```{r worldcloud, fig.cap="Wordcloud based on titles and abstracts (first 100)"}

# thanks to Céline van den Rul https://towardsdatascience.com/create-a-word-cloud-with-r-bde3e7422e8a
# should we add a reference?

wordsforcloud <- strsplit(c(allWorks$TI, allWorks$AB), split = "[[:punct:]|[:space:]]")
wordsforcloud <- tolower(unlist(wordsforcloud))
wordsforcloud <- wordsforcloud[wordsforcloud!=""]
wordsforcloud <- wordsforcloud[!(wordsforcloud%in%stopwords::stopwords())]

wordsforcloud.2 <- sort(table(wordsforcloud), decreasing = TRUE)

wordsforcloud.3 <- as.data.frame(wordsforcloud.2[1:100]) 
colnames(wordsforcloud.3)<-c("words", "freq")

wordcloud(words=wordsforcloud.3$words, freq = wordsforcloud.3$freq, min.freq = 1, max.words=100, random.order=FALSE, rot.per=0.35, colors=params$colors[rev(1:8)])

```
